### ISSUE TITLE
can we have a spidermonkey nightly formula too?

### ISSUE THREAD

**Issue by leobalter** [mathiasbynens/homebrew-ecmascript#4]
https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-mac.zip

please!

**Comment by mathiasbynens** [comment]
I don’t think this is possible as whenever the file at that URL changes, the hash changes as well.

What we want is for #2 to be resolved.

**Comment by leobalter** [comment]
> ... the hash changes as well.

that's why I did not open a PR :)

**Comment by mathiasbynens** [comment]
Gonna close this one. If there is a way to install Homebrew formulae without verifying hashes, let me know!
